post section add to jenkinsfile

diff --git a/JenkinsfileAwsAzure b/JenkinsfileAwsAzure
--- a/JenkinsfileAwsAzure
+++ b/JenkinsfileAwsAzure
@@ -192,4 +192,24 @@ pipeline {
     }
 
 }
+post {
+    always {
+        echo 'Job is completed, doing clean up activities!'
+        // deleteDir() /* clean up our workspace */
+        sh label: "removing running containers",
+        sh "timeout 30 docker ps -aq | xargs -r docker rm -f || true"
+    }
+    success {
+        echo 'Job is completed successfully!'
+    }
+    unstable {
+        echo 'Job is Unstable :/'
+    }
+    failure {
+            echo 'Job is Failed! :('
+            mail to: 'indu.sharma@hpe.com',
+             subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
+             body: "Something is wrong with: ${env.BUILD_URL}"
+    }
+}
 }
